version: "3.8"

services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,sqs,sns,apigateway
      - DEFAULT_REGION=us-east-1

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"